name: test

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.11

      - name: Install dependencies
        run: |
          npm install

      - name: Lint
        run: npm run lint

      - name: Install mongosh
        run: |
          wget https://downloads.mongodb.com/compass/mongodb-mongosh_2.4.2_amd64.deb
          sudo dpkg -i mongodb-mongosh_2.4.2_amd64.deb

      - name: Start MongoDB
        run: |
          npx mongodb-runner start --version 8.0 -- --port 27017 --replSet local_rs
          while ! mongosh --eval 'rs.initiate()'; do sleep 0.5; done

      - name: Run Node tests
        run: npm run coverage

      - name: Run Bun tests
        run: npm run test-bun

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
