name: test

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]
        mongodb-version: ["8.0"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Lint
        run: npm run lint

      - name: Install mongosh
        run: |
          wget https://downloads.mongodb.com/compass/mongodb-mongosh_2.4.2_amd64.deb
          sudo dpkg -i mongodb-mongosh_2.4.2_amd64.deb

      - name: Start MongoDB
        run: |
          npx mongodb-runner start --version ${{ matrix.mongodb-version }} -- --port 27017 --replSet local_rs
          while ! mongosh --eval 'rs.initiate()'; do sleep 0.5; done

      - name: Run tests
        run: npm run coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
  test-bun:
    runs-on: ubuntu-latest
    #needs: test-node

    strategy:
      matrix:
        bun-version: ["1.2.10"]
        mongodb-version: ["8.0"]

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{matrix.bun-version}}

      - name: Install dependencies
        run: |
          bun install

      - name: Install mongosh
        run: |
          wget https://downloads.mongodb.com/compass/mongodb-mongosh_2.4.2_amd64.deb
          sudo dpkg -i mongodb-mongosh_2.4.2_amd64.deb

      - name: Start MongoDB
        run: |
          npx mongodb-runner start --version ${{ matrix.mongodb-version }} -- --port 27017 --replSet local_rs
          while ! mongosh --eval 'rs.initiate()'; do sleep 0.5; done

      - name: Run tests
        run: npm run test-bun
