name: test

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22, 20]
        mongodb-version: ["7.0", "8.0"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Lint
        run: npm run lint

      - name: Install mongosh
        run: |
          wget https://downloads.mongodb.com/compass/mongodb-mongosh_2.4.2_amd64.deb
          sudo dpkg -i mongodb-mongosh_2.4.2_amd64.deb

      - name: Start MongoDB
        run: |
          npx mongodb-runner start --version ${{ matrix.mongodb-version }} -- --port 27017 --replSet local_rs
          while ! mongosh --eval 'rs.initiate()'; do sleep 0.5; done

      - name: Run tests
        run: npm run coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
